version: "3.4"

services:
  mongodb:
    image: mongo
    container_name: mongoDB  
    restart: always
    ports:
    - 27017:27017

  backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./frontend:/app
    environment:
      - apiUrl=http://backend:8080/
    depends_on:
      - backend