version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    expose:
      - "27017"
    ports:
    - 27017:27017

  backend:
    container_name: herder-backend
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./backend:/app
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=herder
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  frontend:
    container_name: herder-frontend
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./frontend:/app
    environment:
      - apiUrl=http://localhost:8080/
    depends_on:
      - backend
    ports:
      - "80:80"
  