name: frontend

defaults:
  run:
    shell: bash
    working-directory: frontend

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: CI
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: herder-frontend
          path: frontend/dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: herder-frontend

      - name: Docker deploy
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: etnoy/herder-frontend:latest
          context: ./frontend
          file: ./frontend/Dockerfile
